"""Hypothesis ORM model representing root-cause theories generated by the RCA agent."""

import uuid
from typing import TYPE_CHECKING

from sqlalchemy import JSON, Boolean, Float, ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.persistence.models.base import GUID, Base, TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from src.persistence.models.incident import Incident


class HypothesisModel(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """Root-cause hypothesis linked to discrete evidence IDs."""

    __tablename__ = "hypotheses"

    incident_id: Mapped[uuid.UUID] = mapped_column(
        GUID, ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False, index=True
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)

    # Stored list of evidence IDs: e.g. ["EV-12", "EV-18"]
    supporting_evidence_ids: Mapped[list[str]] = mapped_column(JSON, default=list, nullable=False)
    contradicting_evidence_ids: Mapped[list[str]] = mapped_column(
        JSON, default=list, nullable=False
    )

    reasoning_summary: Mapped[str] = mapped_column(Text, nullable=False)
    missing_information: Mapped[list[str]] = mapped_column(JSON, default=list, nullable=False)
    suggested_validation: Mapped[list[str]] = mapped_column(JSON, default=list, nullable=False)

    is_selected: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    incident: Mapped["Incident"] = relationship("Incident", back_populates="hypotheses")
